### ISSUE TITLE
Clean up Sass code

### ISSUE THREAD

**Issue by ghost** [vitusignacio/Steven_Hyakusenrenma#10]
https://github.com/vitusignacio/Steven_Hyakusenrenma/blob/6c3d39b3ef09e9fdcf33a849f64b8fa8893720ae/Step1/sass/main.sass#L20

Please clean up your sass code by 
- [x] removing browser prefixes and
- [x] alphabetizing property sort order

Depending on your text editor, you should be able to do this automatically or with some kind of shortcut. 

With Sublime Text Editor, for example, you can highlight a set of properties and hit `F5` to automatically sort them in alphabetical order.

**Comment by vitusignacio** [comment]
@hyakurendev I assume that we would not take care of browser compatibility in this case when we remove browser prefixes.

**Comment by ghost** [comment]
@vitusignacio Yes, please assume we are using an autoprefixer
